### PR TITLE
Added the copy construct to libobliv.a

### PR DESCRIPTION
**Pull request by jackdoerner**
Added the copy construct to libobliv.a and modified makefile to accommodate.

### CODE REVIEW

**Comment by samee** [comment]
Thanks Jack. Is it also possible to move some of the `copy.oh`-specific tests in here? It'd be nice to have some examples that actually exercise these new functions, however trivial they might be.

**Comment by jackdoerner** [comment]
Sure, I can do that. To be clear, you the ones in the "algorithm" repository, right? Or do you mean some others that I'm not aware of?

**Comment by samee** [comment]
You can just copy these over: https://github.com/samee/sqrtOram/tree/master/test
'algorithms' may also have some. Anything with names testshuffle/testswap/testCopy are good candidates. If it depends on anything other than copy.oh, don't use that.

**Comment by jackdoerner** [comment]
OK, there they are.

**Comment by samee** [comment]
Thanks. Merged. Curious: why did you have to use cpp for dependency generation? Was it causing problems?

**Comment by jackdoerner** [comment]
Yep. Interestingly, gcc refuses to do dependency generation for .oc files (at least on my machines), but cpp works without complaint, even though all the same options are passed. Sqrt ORAM uses cpp for dependency generation, which is where I got the idea from, so I suspect this is a problem you have also solved at least once in the past.

**Comment by samee** [comment]
Huh, go past-me!

**Pull request merged**
